### ISSUE TITLE
Target API | No data returned

### ISSUE THREAD

**Issue by Shubh-Nisar** [Neel317/ShopSync#3]
While selecting iPhone in the search bar and selecting Target as the source website, no data is returned.

**Comment by Neel317** [comment]
Ok, it might be an issue on the target public API that is causing this bug, I will check and let you know.

**Comment by Neel317** [comment]
The issue was in the Target public API they were returning empty objects. Handled it in the response in scrapper.py.

**Comment by Neel317** [comment]
I have pushed the changes it is now up and running.
